### PR TITLE
Updated the codemirror dependency.

### PR DESCRIPTION
**Pull request by michaelewens**
This fixed it for me with a development install.  Apologize for possibly following the incorrect procedures for pull requests (mainly a user rather than contributor).

### CODE REVIEW

**Comment by kylebarron** [comment]
I'm guessing this might break it for older JupyterLab versions. Can you try using `*` instead?

**Comment by michaelewens** [comment]
So `"@jupyterlab/codemirror": "*"`? or `"@jupyterlab/codemirror": "*3.0.0"?

**Comment by kylebarron** [comment]
`"@jupyterlab/codemirror": "*"`

**Comment by michaelewens** [comment]
Thanks again.

**Comment by kylebarron** [comment]
Did that work?

**Comment by michaelewens** [comment]
Yes, sorry.

**Pull request merged**
